from pathlib import Path

import numpy as np
from rdkit import Chem


def write_mols_to_gro(mols, box_tensor, output_path):
    """Write RDKit molecules to one GROMACS GRO file.

    Coordinates and ``box_tensor`` are read in angstrom and written in nm.
    Residue metadata is read from ``RES_NAMES``/``RES_NUMS`` when available,
    with atom-level ``res_name``/``global_res_id`` metadata as fallback.

    Parameters
    ----------
    mols : sequence of rdkit.Chem.Mol
        Molecules with one conformer each.
    box_tensor : sequence of float
        Orthorhombic ``[lx, ly, lz]`` or 9-component box tensor in angstrom.
    output_path : str or pathlib.Path
        Output GRO path.
    """
    coordinates, res_names, res_ids, atom_names = [], [], [], []
    global_idx = 0
    for mol in mols:
        if mol is None: continue
        if mol.GetNumConformers() == 0: raise ValueError("Each molecule must contain a conformer.")
        n = mol.GetNumAtoms(); conf = mol.GetConformer(0)
        mol_res_names = mol.GetProp("RES_NAMES").split() if mol.HasProp("RES_NAMES") else None
        mol_res_ids = [int(x) for x in mol.GetProp("RES_NUMS").split()] if mol.HasProp("RES_NUMS") else None
        if mol_res_names is not None and len(mol_res_names) != n: raise ValueError("RES_NAMES must contain one entry per atom.")
        if mol_res_ids is not None and len(mol_res_ids) != n: raise ValueError("RES_NUMS must contain one entry per atom.")
        for aidx, atom in enumerate(mol.GetAtoms()):
            atom.SetIntProp("global_idx", global_idx); coordinates.append(conf.GetAtomPosition(aidx))
            atom_names.append(atom.GetSymbol())
            if mol_res_names is not None: res_names.append(mol_res_names[aidx])
            elif atom.HasProp("res_name"): res_names.append(atom.GetProp("res_name"))
            else: res_names.append("UNL")
            if mol_res_ids is not None: res_ids.append(mol_res_ids[aidx])
            elif atom.HasProp("global_res_id"): res_ids.append(atom.GetIntProp("global_res_id"))
            elif atom.HasProp("res_id"): res_ids.append(atom.GetIntProp("res_id"))
            else: res_ids.append(0)
            global_idx += 1

    coordinates = np.asarray(coordinates, dtype=float).reshape((-1, 3)) if coordinates else np.empty((0, 3), dtype=float)
    box_tensor = [float(x) for x in box_tensor]
    if len(box_tensor) not in (3, 9): raise ValueError("box_tensor must contain either 3 or 9 values.")
    if len(box_tensor) == 3: box_tensor += [0.0] * 6
    tensor_nm = [x / 10.0 for x in box_tensor]
    if all(abs(tensor_nm[i]) < 1e-4 for i in range(3, 9)):
        box_line = f"{tensor_nm[0]:10.5f} {tensor_nm[1]:10.5f} {tensor_nm[2]:10.5f}\n"
    else:
        box_line = (f"{tensor_nm[0]:10.5f} {tensor_nm[4]:10.5f} {tensor_nm[8]:10.5f} "
                    f"{tensor_nm[1]:10.5f} {tensor_nm[2]:10.5f} {tensor_nm[3]:10.5f} "
                    f"{tensor_nm[6]:10.5f} {tensor_nm[7]:10.5f} {tensor_nm[5]:10.5f}\n")

    output_path = Path(output_path)
    with output_path.open("w", buffering=65536) as handle:
        handle.write("Generated by ChemFAST\n"); handle.write(f"{len(coordinates):5d}\n")
        for i, (res_id, res_name, atom_name, xyz) in enumerate(zip(res_ids, res_names, atom_names, coordinates)):
            x, y, z = (float(v) / 10.0 for v in xyz)
            handle.write(f"{int(res_id) % 100000:5d}{str(res_name)[:5]:<5}{str(atom_name)[:5]:>5}"
                         f"{(i + 1) % 100000:5d}{x:8.3f}{y:8.3f}{z:8.3f}\n")
        handle.write(box_line)