name: chemfast

channels:
  - conda-forge

dependencies:
  - python=3.12
  - openbabel
  - pip

  - pip:
      - numpy
      - scipy
      - pandas
      - networkx
      - scikit-learn
      - matplotlib
      - numba
      - MDAnalysis
      - rdkit>=2025.09.5
      - torch
      - torch-geometric
      - pytest
      - -e .
