name: chemfast
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy
  - rdkit=2025.09.5
  - openbabel
  - numba
  - networkx
  - pandas
  - scipy
  - jupyter
  - scikit-learn
  - matplotlib
  - mdanalysis
  - pip:
      - pytest
      - -e .
